/**
 * app/api/nightclaw/digest/route.ts
 * STORY-9.1 — GET /api/nightclaw/digest?date=YYYY-MM-DD
 *
 * Reads the NightClaw digest markdown file and model-stats.json,
 * parses a summary and returns structured JSON.
 *
 * Auth: requireAuth — 401 for unauthenticated requests.
 * Missing digest file: 404.
 * Missing model-stats.json: null (graceful fallback).
 */

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

import { NextResponse } from 'next/server'
import { readFile } from 'fs/promises'
import { requireAuth } from '@/lib/auth/requireRole'
import type { RequireAuthResult } from '@/lib/auth/requireRole'

// ─── Types ────────────────────────────────────────────────────────────────────

interface DigestSummary {
  new_patterns: number
  lessons_extracted: number
  anti_patterns_flagged: number
  open_issues: number
  generated_at: string
}

// model-stats.json schema (as-is passthrough)
type ModelStats = Record<string, unknown> | null

interface DigestResponse {
  date: string
  markdown: string
  summary: DigestSummary
  model_stats: ModelStats
}

// ─── File paths ───────────────────────────────────────────────────────────────

const KIRA_DIR = process.env.KIRA_DIR || '/Users/mariuszkrawczyk/codermariusz/kira'
const DIGEST_DIR = `${KIRA_DIR}/.kira/nightclaw/digest`
const MODEL_STATS_PATH = `${KIRA_DIR}/.kira/nightclaw/model-stats.json`

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Type guard: auth result is an error response */
function isErrorResponse(result: RequireAuthResult): result is NextResponse {
  return result instanceof Response
}

/** Try to read a file; returns null if not found */
async function tryReadFile(filePath: string): Promise<string | null> {
  try {
    return await readFile(filePath, 'utf-8')
  } catch {
    return null
  }
}

/** Read a file; throws if not found (for digest — must return 404) */
async function readFileOrThrow(filePath: string): Promise<string> {
  return readFile(filePath, 'utf-8')
}

/** Get today's date in YYYY-MM-DD format */
function getTodayDate(): string {
  return new Date().toISOString().split('T')[0]!
}

/** Validate YYYY-MM-DD format */
function isValidDate(date: string): boolean {
  return /^\d{4}-\d{2}-\d{2}$/.test(date)
}

// ─── Summary parser ───────────────────────────────────────────────────────────

/**
 * Parse a number from a line like:
 *   - **Nowe wzorce:** 3
 *   - **Nowe lekcje:** 2
 * Returns 0 if not found.
 */
function parseCountFromLine(content: string, label: string): number {
  // Match "**label:** N" patterns (with various separators)
  const re = new RegExp(`\\*\\*${label}[:\\s]*\\*\\*\\s*(\\d+)`, 'i')
  const m = re.exec(content)
  if (m) return parseInt(m[1]!, 10)
  return 0
}

/**
 * Count open_issues:
 * Strategy 1: If "## 🔍 Otwarte problemy" section exists,
 *   count bullet items (`- `) in that section until the next `##` header.
 * Strategy 2: Otherwise, count lines containing "❌" (excluding section headers).
 */
function parseOpenIssues(content: string): number {
  const lines = content.split('\n')

  // Check for "## 🔍 Otwarte problemy" section
  const sectionHeaderRe = /^##\s+.*Otwarte problemy/
  let inSection = false
  let sectionCount = 0
  let foundSection = false

  for (const line of lines) {
    if (sectionHeaderRe.test(line)) {
      inSection = true
      foundSection = true
      continue
    }
    if (inSection) {
      // End of section at next ## header
      if (/^##\s+/.test(line)) {
        inSection = false
        break
      }
      // Count bullet items in section
      if (/^\s*-\s+/.test(line) && line.trim().length > 2) {
        sectionCount++
      }
    }
  }

  if (foundSection) {
    return sectionCount
  }

  // Fallback: count lines with "❌" (excluding ## headers which use ❌ in title)
  let crossCount = 0
  for (const line of lines) {
    // Skip section headers (## lines)
    if (/^##\s+/.test(line)) continue
    if (line.includes('❌')) {
      crossCount++
    }
  }
  return crossCount
}

/**
 * Extract generated_at from the digest.
 * Looks for lines like:
 *   > Wygenerowany: 02:05 AM | ...
 *   *Digest generated by NightClaw 🌙🦉 | 2026-02-25 02:00 UTC*
 * Falls back to ISO date string if not parseable.
 */
function parseGeneratedAt(content: string, date: string): string {
  // Try "> Wygenerowany: HH:MM AM/PM" format
  const wygRe = /Wygenerowany:\s+(\d{2}:\d{2}\s*(?:AM|PM)?)/i
  const wygMatch = wygRe.exec(content)
  if (wygMatch) {
    // Return as "YYYY-MM-DD THH:MM:00Z" approximation
    const timeStr = wygMatch[1]!.trim()
    return `${date} ${timeStr} UTC`
  }

  // Try "*Digest generated ... | YYYY-MM-DD HH:MM UTC*" format
  const generatedRe = /Digest generated.*?\|\s*(\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}\s+UTC)/i
  const generatedMatch = generatedRe.exec(content)
  if (generatedMatch) {
    return generatedMatch[1]!.trim()
  }

  // Fallback: just the date as ISO string
  return `${date}T00:00:00Z`
}

/**
 * Parse the summary from digest markdown content.
 */
function parseDigestSummary(content: string, date: string): DigestSummary {
  const new_patterns = parseCountFromLine(content, 'Nowe wzorce')
  const lessons_extracted = parseCountFromLine(content, 'Nowe lekcje')
  const anti_patterns_flagged = parseCountFromLine(content, 'Anti-patterns flagged')
  const open_issues = parseOpenIssues(content)
  const generated_at = parseGeneratedAt(content, date)

  return {
    new_patterns,
    lessons_extracted,
    anti_patterns_flagged,
    open_issues,
    generated_at,
  }
}

// ─── Route handler ────────────────────────────────────────────────────────────

export async function GET(req: Request): Promise<Response> {
  // 1. Auth check
  const authResult = await requireAuth(req)
  if (isErrorResponse(authResult)) return authResult

  // 2. Parse date param (default: today)
  const url = new URL(req.url)
  const dateParam = url.searchParams.get('date')
  const date = dateParam && isValidDate(dateParam) ? dateParam : getTodayDate()

  // 3. Read digest file — 404 if missing
  const digestPath = `${DIGEST_DIR}/${date}.md`
  let markdown: string
  try {
    markdown = await readFileOrThrow(digestPath)
  } catch {
    return NextResponse.json(
      { error: `Digest not found for date: ${date}` },
      { status: 404 }
    )
  }

  // 4. Read model-stats.json — null if missing (graceful)
  const modelStatsContent = await tryReadFile(MODEL_STATS_PATH)
  let model_stats: ModelStats = null
  if (modelStatsContent !== null) {
    try {
      model_stats = JSON.parse(modelStatsContent) as ModelStats
    } catch {
      // Invalid JSON — return null gracefully
      model_stats = null
    }
  }

  // 5. Parse summary from markdown
  const summary = parseDigestSummary(markdown, date)

  // 6. Build and return response
  const response: DigestResponse = {
    date,
    markdown,
    summary,
    model_stats,
  }

  return NextResponse.json(response)
}
