/**
 * __tests__/api/nightclaw/digest.test.ts
 * STORY-9.1 — Integration tests for GET /api/nightclaw/digest endpoint.
 * TDD: written before implementation (RED phase).
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

// ─── Mock next/server ─────────────────────────────────────────────────────────

class MockNextResponse extends Response {
  static override json(body: unknown, init?: ResponseInit): MockNextResponse {
    return new MockNextResponse(JSON.stringify(body), {
      ...init,
      headers: { 'Content-Type': 'application/json', ...(init?.headers as Record<string, string>) },
    })
  }
}

jest.mock('next/server', () => ({
  NextResponse: MockNextResponse,
}))

// ─── Mock Supabase ────────────────────────────────────────────────────────────

jest.mock('@/lib/supabase/server', () => ({ createClient: jest.fn() }))

// ─── Mock fs/promises ─────────────────────────────────────────────────────────

const mockReadFile = jest.fn()

jest.mock('fs/promises', () => ({
  readFile: (...args: any[]) => mockReadFile(...args),
}))

// ─── Imports (after mocks) ────────────────────────────────────────────────────

import { GET } from '@/app/api/nightclaw/digest/route'
import {
  mockUserSession,
  mockNoSession,
} from '@/__tests__/helpers/auth'
import { mockRequest } from '@/__tests__/helpers/fetch'

// ─── Sample fixture data ──────────────────────────────────────────────────────

const DIGEST_MD = `# NightClaw Digest — 2026-02-25 🌙

> Wygenerowany: 02:05 AM | Model: claude-sonnet-4-6 | Kanał: NightClaw cron

---

## 📊 Podsumowanie dnia

- **Stories zakończone:** EPIC-6 kompletny (22/22 — wszystkie DONE) ✅
- **Błędy agentów:** 3 faile (GLM × STORY-6.3 ×2, GLM × STORY-6.4 ×1)
- **Nowe lekcje:** 2
- **Nowe wzorce:** 3
- **Anti-patterns flagged:** 1

---

## ✅ Patterns (co zadziałało)
- Pattern A
- Pattern B
- Pattern C

## ❌ Anti-patterns (co nie działa)
- Anti-pattern X

## 🔍 Otwarte problemy
- Problem 1 (open)
- Problem 2 (open)

## 🧹 Memory cleanup

---

*Digest generated by NightClaw 🌙🦉 | 2026-02-25 02:00 UTC*
`

const MODEL_STATS_JSON = JSON.stringify({
  models: {
    codex: {
      stories_completed: 28,
      stories_failed: 1,
      success_rate: 0.97,
      avg_duration_min: 3.4,
      last_story_id: 'STORY-9.8',
      stories_with_refactor: 1,
    },
    sonnet: {
      stories_completed: 20,
      stories_failed: 2,
      success_rate: 0.91,
      avg_duration_min: 15.2,
      last_story_id: 'STORY-9.1',
      stories_with_refactor: 0,
    },
  },
  last_updated: '2026-02-25',
  next_review: '2026-03-01',
})

// ─── Tests ────────────────────────────────────────────────────────────────────

describe('GET /api/nightclaw/digest', () => {
  beforeEach(() => jest.clearAllMocks())

  // ── AC-AUTH: 401 without session ──────────────────────────────────────────

  it('returns 401 when unauthenticated (AC-AUTH)', async () => {
    mockNoSession()
    const res = await GET(mockRequest({ url: 'http://localhost/api/nightclaw/digest?date=2026-02-25' }))
    expect(res.status).toBe(401)
    const json = await res.json()
    expect(json).toHaveProperty('error')
  })

  // ── AC-1: Happy path — file exists ────────────────────────────────────────

  it('returns 200 with { date, markdown, summary, model_stats } when file exists (AC-1)', async () => {
    mockUserSession()
    mockReadFile
      .mockResolvedValueOnce(DIGEST_MD)       // digest file
      .mockResolvedValueOnce(MODEL_STATS_JSON) // model-stats.json

    const res = await GET(mockRequest({ url: 'http://localhost/api/nightclaw/digest?date=2026-02-25' }))
    expect(res.status).toBe(200)

    const json = await res.json()
    expect(json).toHaveProperty('date', '2026-02-25')
    expect(json).toHaveProperty('markdown')
    expect(json).toHaveProperty('summary')
    expect(json).toHaveProperty('model_stats')
  })

  it('returns raw markdown string in markdown field (AC-1)', async () => {
    mockUserSession()
    mockReadFile
      .mockResolvedValueOnce(DIGEST_MD)
      .mockResolvedValueOnce(MODEL_STATS_JSON)

    const res = await GET(mockRequest({ url: 'http://localhost/api/nightclaw/digest?date=2026-02-25' }))
    const json = await res.json()

    expect(typeof json.markdown).toBe('string')
    expect(json.markdown).toContain('NightClaw Digest')
  })

  it('returns model_stats as-is from model-stats.json (AC-1)', async () => {
    mockUserSession()
    mockReadFile
      .mockResolvedValueOnce(DIGEST_MD)
      .mockResolvedValueOnce(MODEL_STATS_JSON)

    const res = await GET(mockRequest({ url: 'http://localhost/api/nightclaw/digest?date=2026-02-25' }))
    const json = await res.json()

    expect(json.model_stats).toMatchObject({
      models: expect.any(Object),
      last_updated: '2026-02-25',
    })
    expect(json.model_stats.models).toHaveProperty('codex')
    expect(json.model_stats.models.codex.success_rate).toBe(0.97)
  })

  it('summary has all required fields (AC-1)', async () => {
    mockUserSession()
    mockReadFile
      .mockResolvedValueOnce(DIGEST_MD)
      .mockResolvedValueOnce(MODEL_STATS_JSON)

    const res = await GET(mockRequest({ url: 'http://localhost/api/nightclaw/digest?date=2026-02-25' }))
    const json = await res.json()

    expect(json.summary).toMatchObject({
      new_patterns: expect.any(Number),
      lessons_extracted: expect.any(Number),
      anti_patterns_flagged: expect.any(Number),
      open_issues: expect.any(Number),
      generated_at: expect.any(String),
    })
  })

  // ── AC-2: 404 when file does not exist ────────────────────────────────────

  it('returns 404 when digest file does not exist for given date (AC-2)', async () => {
    mockUserSession()
    const enoent = Object.assign(new Error('ENOENT'), { code: 'ENOENT' })
    mockReadFile.mockRejectedValueOnce(enoent)

    const res = await GET(mockRequest({ url: 'http://localhost/api/nightclaw/digest?date=2026-01-01' }))
    expect(res.status).toBe(404)

    const json = await res.json()
    expect(json).toHaveProperty('error')
  })

  // ── AC-3: No date param → default today ──────────────────────────────────

  it('uses today as default date when no date param provided (AC-3)', async () => {
    mockUserSession()
    mockReadFile
      .mockResolvedValueOnce(DIGEST_MD)
      .mockResolvedValueOnce(MODEL_STATS_JSON)

    const res = await GET(mockRequest({ url: 'http://localhost/api/nightclaw/digest' }))
    // Should attempt to read today's file — either 200 or 404 depending on file existence
    // But it should NOT crash with 500 (date logic should work)
    expect([200, 404]).toContain(res.status)
  })

  it('calls readFile with today\'s date path when no date param (AC-3)', async () => {
    mockUserSession()
    const today = new Date().toISOString().split('T')[0]
    mockReadFile
      .mockResolvedValueOnce(DIGEST_MD)
      .mockResolvedValueOnce(MODEL_STATS_JSON)

    await GET(mockRequest({ url: 'http://localhost/api/nightclaw/digest' }))

    // First readFile call should use today's date
    const firstCall = mockReadFile.mock.calls[0]
    expect(firstCall[0]).toContain(today)
  })

  // ── AC-4: Summary parsing — open_issues ──────────────────────────────────

  it('counts lines with ❌ as open_issues (AC-4)', async () => {
    mockUserSession()
    const mdWith3Issues = `# Digest
## ❌ Anti-patterns
- ❌ Issue one
- ❌ Issue two
## Normal section
- ❌ Another problem
`
    mockReadFile
      .mockResolvedValueOnce(mdWith3Issues)
      .mockResolvedValueOnce(MODEL_STATS_JSON)

    const res = await GET(mockRequest({ url: 'http://localhost/api/nightclaw/digest?date=2026-02-25' }))
    const json = await res.json()

    // open_issues = count of lines with "❌" or section "## 🔍 Otwarte problemy"
    expect(json.summary.open_issues).toBeGreaterThan(0)
  })

  it('counts "## 🔍 Otwarte problemy" section items as open_issues (AC-4)', async () => {
    mockUserSession()
    const mdWithSection = `# Digest

## 🔍 Otwarte problemy
- Problem A
- Problem B
- Problem C

## Other section
- not a problem
`
    mockReadFile
      .mockResolvedValueOnce(mdWithSection)
      .mockResolvedValueOnce(MODEL_STATS_JSON)

    const res = await GET(mockRequest({ url: 'http://localhost/api/nightclaw/digest?date=2026-02-25' }))
    const json = await res.json()

    // 3 items in "Otwarte problemy" section
    expect(json.summary.open_issues).toBe(3)
  })

  it('open_issues is 0 when no ❌ and no Otwarte problemy section (AC-4)', async () => {
    mockUserSession()
    const cleanMd = `# Digest
## ✅ Everything fine
- All good here
`
    mockReadFile
      .mockResolvedValueOnce(cleanMd)
      .mockResolvedValueOnce(MODEL_STATS_JSON)

    const res = await GET(mockRequest({ url: 'http://localhost/api/nightclaw/digest?date=2026-02-25' }))
    const json = await res.json()

    expect(json.summary.open_issues).toBe(0)
  })

  // ── AC-4: Summary parsing — new_patterns ─────────────────────────────────

  it('parses new_patterns from "Nowe wzorce" in markdown (AC-4)', async () => {
    mockUserSession()
    const mdWithPatterns = `# Digest
## 📊 Podsumowanie dnia
- **Nowe wzorce:** 3
- **Nowe lekcje:** 2
- **Anti-patterns flagged:** 1
`
    mockReadFile
      .mockResolvedValueOnce(mdWithPatterns)
      .mockResolvedValueOnce(MODEL_STATS_JSON)

    const res = await GET(mockRequest({ url: 'http://localhost/api/nightclaw/digest?date=2026-02-25' }))
    const json = await res.json()

    expect(json.summary.new_patterns).toBe(3)
  })

  it('parses lessons_extracted from "Nowe lekcje" in markdown (AC-4)', async () => {
    mockUserSession()
    const mdWithLessons = `# Digest
## 📊 Podsumowanie dnia
- **Nowe wzorce:** 1
- **Nowe lekcje:** 5
`
    mockReadFile
      .mockResolvedValueOnce(mdWithLessons)
      .mockResolvedValueOnce(MODEL_STATS_JSON)

    const res = await GET(mockRequest({ url: 'http://localhost/api/nightclaw/digest?date=2026-02-25' }))
    const json = await res.json()

    expect(json.summary.lessons_extracted).toBe(5)
  })

  it('parses anti_patterns_flagged from "Anti-patterns flagged" in markdown (AC-4)', async () => {
    mockUserSession()
    const mdWithAntiPatterns = `# Digest
## 📊 Podsumowanie dnia
- **Anti-patterns flagged:** 2
`
    mockReadFile
      .mockResolvedValueOnce(mdWithAntiPatterns)
      .mockResolvedValueOnce(MODEL_STATS_JSON)

    const res = await GET(mockRequest({ url: 'http://localhost/api/nightclaw/digest?date=2026-02-25' }))
    const json = await res.json()

    expect(json.summary.anti_patterns_flagged).toBe(2)
  })

  it('defaults summary numbers to 0 when not found in markdown (AC-4)', async () => {
    mockUserSession()
    const minimalMd = `# Digest\n\nJust some text\n`
    mockReadFile
      .mockResolvedValueOnce(minimalMd)
      .mockResolvedValueOnce(MODEL_STATS_JSON)

    const res = await GET(mockRequest({ url: 'http://localhost/api/nightclaw/digest?date=2026-02-25' }))
    const json = await res.json()

    expect(json.summary.new_patterns).toBe(0)
    expect(json.summary.lessons_extracted).toBe(0)
    expect(json.summary.anti_patterns_flagged).toBe(0)
    expect(json.summary.open_issues).toBe(0)
  })

  // ── generated_at parsing ──────────────────────────────────────────────────

  it('extracts generated_at from "Wygenerowany" line in digest (AC-1)', async () => {
    mockUserSession()
    const mdWithTimestamp = `# Digest
> Wygenerowany: 02:05 AM | Model: claude-sonnet-4-6 | Kanał: NightClaw cron

Some content.
`
    mockReadFile
      .mockResolvedValueOnce(mdWithTimestamp)
      .mockResolvedValueOnce(MODEL_STATS_JSON)

    const res = await GET(mockRequest({ url: 'http://localhost/api/nightclaw/digest?date=2026-02-25' }))
    const json = await res.json()

    // generated_at should be a non-empty string
    expect(typeof json.summary.generated_at).toBe('string')
    expect(json.summary.generated_at.length).toBeGreaterThan(0)
  })

  it('falls back to ISO date string for generated_at when not parseable (AC-1)', async () => {
    mockUserSession()
    const mdNoTimestamp = `# Digest\nSome content without timestamp\n`
    mockReadFile
      .mockResolvedValueOnce(mdNoTimestamp)
      .mockResolvedValueOnce(MODEL_STATS_JSON)

    const res = await GET(mockRequest({ url: 'http://localhost/api/nightclaw/digest?date=2026-02-25' }))
    const json = await res.json()

    expect(typeof json.summary.generated_at).toBe('string')
    expect(json.summary.generated_at.length).toBeGreaterThan(0)
  })

  // ── model_stats missing gracefully ───────────────────────────────────────

  it('returns null for model_stats when model-stats.json is missing (graceful)', async () => {
    mockUserSession()
    const enoent = Object.assign(new Error('ENOENT'), { code: 'ENOENT' })
    mockReadFile
      .mockResolvedValueOnce(DIGEST_MD)
      .mockRejectedValueOnce(enoent) // model-stats.json missing

    const res = await GET(mockRequest({ url: 'http://localhost/api/nightclaw/digest?date=2026-02-25' }))
    expect(res.status).toBe(200) // should not 500

    const json = await res.json()
    expect(json.model_stats).toBeNull()
  })

  // ── FIXTURE integration: counts open_issues from full DIGEST_MD ──────────

  it('counts open_issues correctly from full fixture digest (AC-4)', async () => {
    mockUserSession()
    mockReadFile
      .mockResolvedValueOnce(DIGEST_MD)
      .mockResolvedValueOnce(MODEL_STATS_JSON)

    const res = await GET(mockRequest({ url: 'http://localhost/api/nightclaw/digest?date=2026-02-25' }))
    const json = await res.json()

    // DIGEST_MD has:
    // - Section "## 🔍 Otwarte problemy" with 2 bullet items
    // - Section "## ❌ Anti-patterns" which is a heading (not counted as ❌ line)
    // - "❌ Anti-patterns (co nie działa)" in section header
    // open_issues should be 2 (from Otwarte problemy section items)
    expect(json.summary.open_issues).toBe(2)
  })
})
